[package]
name = "practice-toy-lang-interpreter-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name="toy_lang"
path="src/lib.rs"

[[bin]]
name="lexer"
path="bin/lexer.rs"

[dependencies]
